evaluate usage_main
evaluate Call_Types
EVALUATE countries



--1) Adding column to usage main table from counties table


evaluate
(
	addcolumns(Usage_Main,"country",RELATED(Countries[Country]))

)



-- 2) Group billable amount by call type
evaluate 
		(
			SUMMARIZE
					(
					usage_main,
					Call_Types[Call Type Descripion],
					"Total billable amount",sum(usage_main[billable amount])
					
								)
		)
		


-- 3) Shows only countries in region 'Americas'
EVALUATE
CALCULATETABLE (Countries, Countries[Region] ="Americas")



--EXTRA	
-- 4) Left join between usage main and countries	
evaluate
Filter(NATURALLEFTOUTERJOIN (Usage_Main,Countries),Countries[Country]="Israel")



